#' Read CSV file generated by FDB
#'
#' Read a CSV file generated by Ferjedatabanken.
#'
#' @param file Path to file. See \code{\link[readr]{read_file}} for details.
#' @param total Extract total values.
#' @param unparsed Return unparsed data frame.
#'
#' @return A data frame.
#' @export
read_fdb_csv <- function(file, total = FALSE, unparsed = FALSE) {
  csv_pages <- readr::read_file(file, readr::locale(encoding = "latin1")) %>%
    stringr::str_split("\n[^\n]*Side \\d[^\n]*\n") %>%
    purrr::flatten_chr()

  df <- purrr::map_df(csv_pages, parse_csv_page)

  if (unparsed) return(df)

  type <- unique(df$type)
  if ("subtype" %in% names(df)) {
    subtype <- unique(df$subtype)
  } else {
    subtype <- NULL
  }

  if (stringr::str_detect(type, "^Variasjonskurver")) {
    if (identical(subtype, "D\u00f8gnvariasjon")) {
      df <- parse_variasjonskurver_dognvariasjon(df, total)
    } else if (identical(subtype, "Ukesvariasjon")) {
      if (total) warning("Parameter \"total\" not implemented.")
      df <- parse_variasjonskurver_ukesvariasjon(df)
    } else if (identical(subtype, "\u00c5rsvariasjon")) {
      df <- parse_variasjonskurver_aarsvariasjon(df, total)
    } else {
      stop("Unknown error.")
    }
  } else if (identical(type, "Trafikkindeks") ||
             identical(type, "Begrenset trafikkindeks")) {
    if (identical(subtype, "\u00c5rsindeks")) {
      df <- parse_trafikkindeks_aarsindeks(df, total)
    } else if (identical(subtype, "Kvartalsindeks")) {
      df <- parse_trafikkindeks_kvartalsindeks(df, total)
    } else if (identical(subtype, "Siste 12 m\u00e5neder")) {
      df <- parse_trafikkindeks_siste_12_maaneder(df, total)
    } else {
      stop("Unknown error.")
    }
  } else if (identical(type, "Trafikkverdier")) {
    if (total) warning("Parameter \"total\" ignored.")
    df <- parse_trafikkverdier(df)
  } else if (identical(type, "Produksjon")) {
    df <- parse_produksjon(df, total)
  } else if (stringr::str_detect(type, "^Sonefordeling")) {
    df <- parse_sonefordeling(df, total)
  } else {
    warning("Unimplemented file type. Returning unparsed data frame.")
  }

  df
}
