#' Read CSV file generated by FDB
#'
#' Read a CSV file generated by Ferjedatabanken.
#'
#' @param file Path to file
#'
#' @return A data frame.
#' @export
read_fdb_csv <- function(file) {
  checkmate::assertFile(file, access = "r")

  csv_lines <- readr::read_lines(file) %>%
    iconv("latin1", "utf8")

  csv_pages <- paginate(csv_lines)

  df <- lapply(csv_pages, parse_csv_page) %>%
    dplyr::bind_rows()

  checkmate::assertDataFrame(df, min.cols = 14)

  type <- unique(df$type)
  subtype <- unique(df$subtype)

  if (identical(type, "Variasjonskurver")) {
    if (identical(subtype, "D\u00f8gnvariasjon")) {
      df <- parse_variasjonskurver_dognvariasjon(df)
    } else if (identical(subtype, "Ukesvariasjon")) {
      df <- parse_variasjonskurver_ukesvariasjon(df)
    } else if (identical(subtype, "\u00c5rsvariasjon")) {
      df <- parse_variasjonskurver_aarsvariasjon(df)
    } else {
      stop("Unknown error.")
    }
  } else if (identical(type, "Trafikkindeks") ||
             identical(type, "Begrenset trafikkindeks")) {
    if (identical(subtype, "\u00c5rsindeks")) {
      df <- parse_trafikkindeks_aarsindeks(df)
    } else if (identical(subtype, "Kvartalsindeks")) {
      df <- parse_trafikkindeks_kvartalsindeks(df)
    } else if (identical(subtype, "Siste 12 m\u00e5neder")) {
      df <- parse_trafikkindeks_siste_12_maaneder(df)
    } else {
      stop("Unknown error.")
    }
  }
  else {
    warning("Unimplemented file type. Returning unparsed data frame.")
  }

  df
}
